FROM node:lts-alpine AS build-stage

# делаем каталог 'app' текущим рабочим каталогом
WORKDIR /app

# копируем оба 'package.json' и 'package-lock.json' (если есть)
COPY package*.json ./

# устанавливаем зависимости проекта
RUN npm install

# копируем файлы и каталоги проекта в текущий рабочий каталог (т.е. в каталог 'app')
COPY . .

# задаем адрес API как переменную окружения
ARG VITE_APP_API_URL
ENV VITE_APP_API_URL=$VITE_APP_API_URL

# собираем приложение для production с минификацией
RUN npm run build

# Stage 2: Запускаем Nginx и копируем собранный фронтенд
FROM nginx:1.21
# Копируем файл конфигурации Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Копируем собранный фронтенд из первого стейджа
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Запускаем Nginx
CMD ["nginx", "-g", "daemon off;"]